### ISSUE TITLE
Fails on null attributes

### ISSUE THREAD

**Issue by cetetesoft** [rweber7912/timezoned#1]
Hi. Thanks for this trait. It's just what I was looking for.
I have found a small bug - when a timestamp field is null in the database, it is converted to a new Carbon object with the current timestamp.
The workaround I'm using is as follows:
```
trait TimezoneTrait{
  use Timezoned {
    applyTimezone as defaultApplyTimezone;
  }

  protected function applyTimezone($value,$fromTz,$toTz){
    // Bug fix
    if(!$value)
      return $value;
    else
      return $this->defaultApplyTimezone($value,$fromTz,$toTz);
  }
}
```

**Comment by rweber7912** [comment]
Nice one! Thanks for sharing your fix. I'll update the repo.
